language: php

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - mysql

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - mysql -e 'create database laravel_migrate_check;' -uroot
